gamemodes/sss/core/player/tool-tips.pwn

This fixes the tool-tip text in regards to the new wheel repair update.

Tool-Tip text fix

---

gamemodes/sss/core/player/core.pwn
gamemodes/sss/core/vehicle/lock.pwn

Fixed the crash when someone tries to enter your vehicle as passenger
with G and the players nearby gets crashed.

Fixed client crash

---

gamemodes/ScavengeSurvive.pwn
gamemodes/sss/core/item/locator.pwn
gamemodes/sss/core/server/init.pwn
gamemodes/sss/core/vehicle/trunk.pwn
gamemodes/sss/core/world/explosive.pwn

I had an idea track down players so I made it. Basically how it works
is, you have to craft a "Locator"  (i couldn't came up with a better name
lol) item on workbench (mobile phone + receiver), then you can sync it
with a mobile phone. After that, wherever you put the mobile phone:
player's backpack, vehicle's trunk, large box you can track it down. It
is useful to track player's bases, if you can hide the mobile well in
his/her stuffs.
While testing, I discovered that the GetContainerTrunkVehicleID() and
doesn't work properly, so I fixed it.
Also I switched up GetContainerBagItem() and GetContainerPlayerBag(),
because when I wanted to detonate the bomb in my backpack, while wearing
it, the script stopped at GetContainerBagItem(), and returned 0.0, 0.0,
0.0 coordinates.

New item: Locator

---

gamemodes/sss/utils/tickcountfix.pwn

Current realization GetTickCountDifference is not working properly.
CELLMAX and CELLMIN simulates what we have 99 as max and -100 as min values.
```Pawn
#include <a_samp>
#define CELLMAX 99
#define CELLMIN -100
stock abs(value)
{
return value < 0 ? -value : value;
}
stock intdiffabs(tick1, tick2)
{
if(tick1 > tick2)
return abs(tick1 - tick2);
else
return abs(tick2 - tick1);
}
stock GetTickCountDifference(a, b)
{
if ((a < 0) && (b > 0))
{
new dist;
dist = intdiffabs(a, b);
if(dist > CELLMAX)
return intdiffabs(a - CELLMAX, b - CELLMAX);
else
return dist;
}
return intdiffabs(a, b);
}
stock GetTickDiff(newtick, oldtick)
{
if (oldtick < 0 && newtick >= 0) {
return newtick - oldtick;
} else if (oldtick >= 0 && newtick < 0 || oldtick > newtick) {
return (CELLMAX - oldtick + 1) - (CELLMIN - …
```

Fix for GetTickCountDifference

---

gamemodes/sss/core/player/tutorial.pwn

small uptade to remove items from inventory

tutorial update

---

gamemodes/ScavengeSurvive.pwn
gamemodes/sss/core/item/witcheshat.pwn

Added witcheshat offset
*Loot not implemented

WitchesHat offset

---

gamemodes/sss/core/server/init.pwn
gamemodes/sss/core/world/water-purifier.pwn

An old code I made a while ago

Finished water purifier

---

gamemodes/ScavengeSurvive.pwn
gamemodes/sss/core/char/food.pwn
gamemodes/sss/core/player/commands.pwn
gamemodes/sss/core/player/widescreen.pwn
gamemodes/sss/core/ui/watch.pwn

hopefully provides players with a way to choose a working UI scaling profile to fit their game

---

gamemodes/sss/core/char/food.pwn

I corrected it that way, but maybe there could be another one.

Fixing hunger bar conflict with other bars

---

gamemodes/sss/core/player/widescreen.pwn

Setting a standard scale and a message for those who just registered.

Setting a default scale

---

gamemodes/sss/world/houseloot.pwn

It was spawning military weapons on it

Fixing the loot of the houses

---

gamemodes/sss/core/itemtype/backpack.pwn

Make the item go to the backpack when the inventory is full.

Make the item go to the backpack.

---

gamemodes/sss/core/admin/level4.pwn
gamemodes/sss/core/char/drugfx.pwn
gamemodes/sss/core/server/weather.pwn

Fix weather

---

gamemodes/sss/core/server/init.pwn

using a screwdriver he builds a defense.

Fix locker and largeframe craft

---

gamemodes/sss/core/player/death.pwn

This fixes a bug that occurred when someone logged out at the death screen, killing other players.

Fix death bug

---

gamemodes/sss/core/ui/hold-action.pwn
gamemodes/sss/core/world/fuel.pwn

for some reason the Bar always disappeared the first time it was activated. I added this to fix it.

Fixed first hold action

---

docs/src/pages/servers.md

rm Scavenge Nostalgia
add "New Age"

tweak(docs): /servers updated

---

docs/src/pages/servers.md

Dayz ~ Brasa Survival Zone PC/Mobile

tweak(docs/servers): add br server

---

Taskfile.yml

Invalid schema version in Taskfile

---

docs/src/data/servers.js

server listing update
